version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - WORKER_API_KEY=worker-secret-key
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./APP_DATA:/app/APP_DATA
    networks:
      - health-app-network
    restart: unless-stopped

  # Background Worker Service
  worker:
    build:
      context: ./worker
      dockerfile: ../docker/worker.Dockerfile.dev
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://backend:3001
      - WORKER_INTERVAL=30000
      - SEED_RETRY_ATTEMPTS=5
      - SEED_RETRY_DELAY=2000
      - WORKER_API_KEY=worker-secret-key
    volumes:
      - ./worker:/app
      - /app/node_modules
      - ./APP_DATA:/app/APP_DATA
    depends_on:
      - backend
    networks:
      - health-app-network
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - health-app-network
    restart: unless-stopped

networks:
  health-app-network:
    driver: bridge

volumes:
  node_modules:
